### ISSUE TITLE
CS Clubs

### ISSUE THREAD

**Issue by iriszhong7** [bitprj/marketing#17]
# CS:
- [x] AI Society
- [ ] #include
- [ ] DCSC
- [ ] Women in Computer Science
  - crash courses/workshops in different cs programs 
- [ ] Davis Computer Science Club
  - git/various cs companies workshops
  - collaborations with companies (ex.uber) in hosting events/panels
- [ ] Computer Science for Kids
  - recruits volunteers to teach weekly lesson plans/volunteers can create their own lesson plans
- [ ] SacHacks
  - github workshops
  - collaborations with companies (IBM)
  - sachacks hackathon event

[Find more on AggieLife](https://aggielife.ucdavis.edu/organizations?categories=9248)

**Comment by shreythecray** [comment]
We've reached out to CS4K (Computer Science for Kids) for PrimaryEd already - go ahead and contact the other clubs and see if they're interested in setting up a call.

**Comment by shreythecray** [comment]
- [ ] Delete this file https://github.com/bitprj/marketing/blob/master/clubs.md
