### ISSUE TITLE
[Content Team] Writing Content Task

### ISSUE THREAD

**Issue by nians520** [bitprj/marketing#56]
# Writing Beginner Task
*Please complete the following checklists and notify the Technical Writing Lead when you’re done.*

For ALL files:
- Copy the test file
- Push it into the repository
- Label it yourname_writingtest.md

## Edit the email blurb for the Twitter IMC webinar:
- [x] Grammar, punctuation, spelling check
- [x] Ensure smooth transition from one segment of the email to another
## Completion
- [x] Notify Steven Nian that you have completed this

**Comment by vkxu657** [comment]
Finished editing the doc but there still seems to be some sections that need to be added in. Lmk if/when they'll be finished so that I can look them over.
