### ISSUE TITLE
Twitter Graphic for Hubspot Email

### ISSUE THREAD

**Issue by rochelledai** [bitprj/marketing#58]
**Objectives**: Create a variant of the [postman graphic](https://drive.google.com/open?id=1rDO8pdqy4U1g7TTdaSBrLdqli7R8Pvhq) to communicate students using twitter data and APIs. 
**Assignees**: @lillyp3 @adrienne-lee 
**Deadline**: **Wednesday, 4/29/20**

### Detailed Notes
Students used the Twitter API to analyze and gain insights with location based Covid-19 data. Bit Project hosted a computational social science boot camp targeted towards communication majors to teach them code and how to use the Twitter API to perform sentiment analysis and data visualization.

TO DO:

- [ ] First Iteration/ mock up in Illustrator showing layout - @lillyp3 , @adrienne-lee 

- [ ] Change color scheme to show relation to Twitter?

- [ ] Hubspot Email layout - @rochelledai 

Assets needed

- Students collaborating - should be main focus

- Twitter Tweet Panels - secondary focus

**Comment by lillyp3** [comment]
**1. Brainstorm/Sketches** 4/26 - 4/28

Rochelle begins the brainstorm processing with sketches of people handing code to each other, or a group of people working on one code block together.
![Image from iOS](https://user-images.githubusercontent.com/63167588/80658660-907c7300-8a3b-11ea-8633-87165aa64596.jpg)
![Image from iOS copy](https://user-images.githubusercontent.com/63167588/80658663-91ada000-8a3b-11ea-880a-9fa3e6a21ccb.jpg)

I add combine her two ideas in my final sketch where a group of three people are working on a large code panel, which includes passing a tweet.
![Untitled_Artwork copy](https://user-images.githubusercontent.com/63167588/80658719-bdc92100-8a3b-11ea-9be6-efe6a8952f64.jpg)

The graphic needs to include:

- collaboration
- tweets/twitter related panels
- friendly style of characters/people
- incorporate the twitter blue color scheme

**First Iteration** 4/27
I create a rough mockup of the graphic and experiment with different colors 
![TwitterAPIGraphicMock2](https://user-images.githubusercontent.com/63167588/80658935-52cc1a00-8a3c-11ea-88d0-ddc00deeec1c.png)

- all the colors are very muted and there is no coherent color scheme
- the shapes below the people are unnecessary and confusing

**Second Iteration** 4/28
![TwitterAPIGraphic(FinalMock)](https://user-images.githubusercontent.com/63167588/80659006-8c048a00-8a3c-11ea-992a-17f418f18a8c.png)

- I brighten the colors and incorporate more blue to go with the twitter theme
- I fix the graphics on the panels to be more interesting, and include different floating tweet panels
- I add a blue outline to create a cohesive style

Feedback from Daniel and Rochelle:
- eliminate the outlines
- change the blue panel to match the Twitter brand
- make the details on the panel stand out

![TwitterAPIGraphic(Mock7)](https://user-images.githubusercontent.com/63167588/80659204-1fd65600-8a3d-11ea-9517-feb6e9f1380e.png)

- I changed the blues and rounded the corners of the panels
- I eliminated the yellow blocks of code and shifted to shades of blue and white

**Comment by rochelledai** [comment]
Final, 4/30

- changed colors

- added details to code panel

![TwitterAPIGraphic_dark_Rochelle2](https://user-images.githubusercontent.com/63178891/83343891-3d554480-a2b5-11ea-85e0-cb4654df3d88.png)

![TwitterAPIgraphic_light_Rochelle1](https://user-images.githubusercontent.com/63178891/83343892-40503500-a2b5-11ea-9e57-74806353ed52.png)
