### ISSUE TITLE
Website Icons

### ISSUE THREAD

**Issue by rochelledai** [bitprj/marketing#59]
**Objectives**: Create 3 icons representing different subject areas to be used on the Bit Project website.
**Assignees**: @lillyp3 @adrienne-lee 
**Deadline**: **Sunday, 4/26/20**

### Detailed Notes
Icons should be "simple and 2d". 
Icons needed:

- [ ] Public Health

- [ ] Psychology

- [ ] Political Science

TO DO:

- Sketches - @adrienne-lee , @lillyp3 
- Finalizing in Illustrator - TBD, whoever is more available

**Comment by lillyp3** [comment]
1. Brainstorm and Sketches (Lilly and Adrienne) 4/25
![IMG_1795](https://user-images.githubusercontent.com/63167588/80301357-8c5d0680-8758-11ea-8ed4-d058b93c1929.JPG)
![Political_science_icons](https://user-images.githubusercontent.com/63167588/80301362-95e66e80-8758-11ea-985c-3141e8742e6c.jpeg)
![Psychology_icons](https://user-images.githubusercontent.com/63167588/80301363-967f0500-8758-11ea-9db7-6ab75ac02aaf.jpeg)
![Public_Health_icons](https://user-images.githubusercontent.com/63167588/80301365-967f0500-8758-11ea-863b-a33bebbbb350.jpeg)

2. First Iteration of digitizing the icons 4/25
![Bit_Website_Icons-01](https://user-images.githubusercontent.com/63167588/80301418-e067eb00-8758-11ea-8168-5759a073f592.png)

3. Second Iteration 4/25
Psychology
![Bit_Website_Psychology-01](https://user-images.githubusercontent.com/63167588/80301446-0097aa00-8759-11ea-8ede-3dc7f1c603ab.png)

Political Science
![Bit_Website_Political_Science-02](https://user-images.githubusercontent.com/63167588/80301455-0ee5c600-8759-11ea-8d20-6f6abace6bb1.png)

Public Health
![Bit_Website_IconsPublicHealth-03](https://user-images.githubusercontent.com/63167588/80301459-173e0100-8759-11ea-8ce2-213fc7aa9321.png)
