### ISSUE TITLE
Creating New Brand Guidelines

### ISSUE THREAD

**Issue by vanvvo** [bitprj/marketing#91]
# Due Date: 7/8/2020

### Objectives:
* make presentations less distracting
* create more options for presentation themes

### Specifications:
- [x] make the background white
- [x] find different fonts that can work
- [x] make sketches of different presentation elements
- [x] find more colors for presentations
- [x] create more creative elements (play around with transparency and sparsity)

### Submission/Sharing:
* presenting in a meeting

**Comment by shreythecray** [comment]
Great job!
