### ISSUE TITLE
Social Media Posts

### ISSUE THREAD

**Issue by vanvvo** [bitprj/marketing#92]
# Due Date: 7/4/2020

### Objectives:
* design ideas for posts (member spotlights, speaker highlights, and blog authors)
* make a Figma inspiration board with ideas (colors, theme, and layout)

### Specifications:
- [x] search Instagram for similar organizations as Bit Project (modern, college student vibes)
- [x] find color schemes that fit Bit Project (not super vibrant, pastel)
- [x] outline post layouts
- [x] keep in mind professionalism (for LinkedIn)

### Submission/Sharing:
* presenting in a meeting

**Comment by shreythecray** [comment]
Still needs some work but you're on the right track
