### ISSUE TITLE
Bit Project Art Style

### ISSUE THREAD

**Issue by vanvvo** [bitprj/marketing#94]
# Due Date: 7/5/2020

### Objectives:
* expand graphics library
* understand Bit Project art style

### Specifications:
- [x] create different body structures
- [x] work on closing the gap in art styles (facial features, types of lines, color)
- [x] understand the 2-D backgrounds
- [x] create clear layers for easy editing

### Submission/Sharing:
* presenting in a meeting

**Comment by shreythecray** [comment]
Ahh you're doing an amazing job on this and I'm excited to see what else you come up with!
